---
classes                           :
                                    - moosefs::repo
                                    - moosefs::common
                                    - moosefs::mfsmaster
                                    - moosefs::mfscgi

leciao_host_roles                 :
                                    - dont_dnsmasq

