---
classes                           :
                                    - moosefs::repo
                                    - moosefs::mfsmaster
                                    - moosefs::common
#                                    - moosefs::user
#                                    - moosefs::common

leciao_host_roles                 :
                                    - dont_dnsmasq

